package com.tvpage.lib.utils;

/**
 * Created by MTPC-110 on 11/30/2017.
 */

public class Constants {

    public static final String BUNDLE_KEY_VIDEO_DETAIL_DATA_KEY = "BUNDLE_KEY_VIDEO_DETAIL_DATA_KEY";
    public static final String BUNDLE_KEY_VIDEO_DETAIL_SCREEN_DETERMINATION_KEY = "BUNDLE_KEY_VIDEO_DETAIL_SCREEN_DETERMINATION_KEY";
    public static final String BUNDLE_KEY_VIDEO_DETAIL_SCREEN_SIDEBAR_VALUE = "BUNDLE_KEY_VIDEO_DETAIL_SCREEN_SIDEBAR_VALUE";
    public static final String BUNDLE_KEY_VIDEO_DETAIL_SCREEN_CAROUSEL_VALUE = "BUNDLE_KEY_VIDEO_DETAIL_SCREEN_CAROUSEL_VALUE";
    public static final String BUNDLE_KEY_VIDEO_DETAIL_SCREEN_SOLO_VALUE = "BUNDLE_KEY_VIDEO_DETAIL_SCREEN_SOLO_VALUE";
    public static final String BUNDLE_KEY_VIDEO_LIST = "BUNDLE_KEY_VIDEO_LIST";
    public static final String BUNDLE_KEY_VIDEO_POSITION = "BUNDLE_KEY_VIDEO_POSITON";
}
